version: '3'
name: text-analyzer
services:
    text-analyzer-backend:
        image: somapp/text-analyzer-backend:latest
        restart: on-failure
        ports:
            - '8080:8080'
    text-analyzer-frontend:
        image: somapp/text-analyzer-frontend:latest
        restart: on-failure
        ports:
            - '4200:4200'