version: '3'
name: text-analyzer
services:
    text-analyzer-backend:
        build:
              context: ./backend/text-analyzer/
              dockerfile: Dockerfile
        restart: on-failure
        ports:
            - '8080:8080'
    text-analyzer-frontend:
        build:
            context: ./frontend/text-analyzer-angular/
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - '4200:4200'